### ISSUE TITLE
Multi test suit tags in the test result xml not support in sphinx-test-reports v0.3.7

### ISSUE THREAD

**Issue by sky-dream** [useblocks/sphinx-test-reports#40] opened 2022-08-15 05:21 UTC
Should be fixed with #9.
As I'm not using Google test, I'm unable to test it.

_Originally posted by @danwos in https://github.com/useblocks/sphinx-test-reports/issues/7#issuecomment-525141336_

current now in the sphinx-test-reports v0.3.7, the Multi test suit tags import still not supported, only the test cases in the 1st test suit tag is imported by the tool, the later test suit tag is ignored.

below is 1 google test output xml for your reference and test, pls help check this issue is fixed or not, tks.
```html
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="6" failures="1" disabled="0" errors="0" time="0.001" timestamp="2022-08-15T09:08:41.743" name="AllTests">
  <testsuite name="TimerTest" tests="4" failures="0" disabled="0" skipped="0" errors="0" time="0" timestamp="2022-08-15T09:08:41.743">
    <testcase name="test_Timer_increment" status="run" result="completed" time="0" timestamp="2022-08-15T09:08:41.743" classname="TimerTest" />
    <testcase name="test_Timer_checkTime" status="run" result="completed" time="0" timestamp="2022-08-15T09:08:41.743" classname="TimerTest" />
    <testcase name="test_Timer_getdT" status="run" result="completed" time="0" timestamp="2022-08-15T09:08:41.743" classname="TimerTest" />
    <testcase name="test_Timer_getCurrentTime" status="run" result="completed" time="0" timestamp="2022-08-15T09:08:41.743" classname="TimerTest" />
  </testsuite>
  <testsuite name="TimerCounterImplTest" tests="2" failures="1" disabled="0" skipped="0" errors="0" time="0.001" timestamp="2022-08-15T09:08:41.743">
    <testcase name="CheckTimerFunction_Init" status="run" result="completed" time="0" timestamp="2022-08-15T09:08:41.743" classname="TimerCounterImplTest">
      <failure message="C:\CPPComponent\CPPTimeCounter\tst\tests\UT\test_c_TimeCounter_timecounter_5msImpl.cpp:85&#x0A;Expected equality of these values:&#x0A;  TimerValue&#x0A;    Which is: 500&#x0A;  testOuputs.m_TimerCurrentValue&#x0A;    Which is: 0" type=""><![CDATA[C:\CPPComponent\CPPTimeCounter\tst\tests\UT\test_c_TimeCounter_timecounter_5msImpl.cpp:85
Expected equality of these values:
  TimerValue
    Which is: 500
  testOuputs.m_TimerCurrentValue
    Which is: 0]]></failure>
      <failure message="C:\CPPComponent\CPPTimeCounter\tst\tests\UT\test_c_TimeCounter_timecounter_5msImpl.cpp:86&#x0A;Expected equality of these values:&#x0A;  TimeReached&#x0A;    Which is: true&#x0A;  testOuputs.m_TimeReached&#x0A;    Which is: false" type=""><![CDATA[C:\CPPComponent\CPPTimeCounter\tst\tests\UT\test_c_TimeCounter_timecounter_5msImpl.cpp:86
Expected equality of these values:
  TimeReached
    Which is: true
  testOuputs.m_TimeReached
    Which is: false]]></failure>
    </testcase>
    <testcase name="CheckTimerFunction_StartTimer" status="run" result="completed" time="0.001" timestamp="2022-08-15T09:08:41.743" classname="TimerCounterImplTest" />
  </testsuite>
</testsuites>
```

**Comment by danwos** [comment] 2022-08-15 06:55
Nested testsuites are supported by #31.
It got released with 0.3.7.
Your use case should work.

What does the rst-code look like? What directives are used and how are they configured?

**Comment by sky-dream** [comment] 2022-08-20 03:25
needs directive test-results is used in the .rst file as below.
```
.. test-results:: ./doc/GTest_Report_UnitTest.xml
```

**Comment by santiagopagani** [comment] 2022-09-23 08:23
I can confirm this issue. I have a GTEST xml file with multiple (not nested) test suites.
For example:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="13" failures="0" disabled="0" errors="0" timestamp="2022-09-22T10:45:08" time="0.001" name="AllTests">
  <testsuite name="UnitTestPortSenderExtensionCurrentStorage" tests="1" failures="0" disabled="0" errors="0" time="0">
    <testcase name="TEST_UNIT_DADDY_SENDER_TExtensionCurrentStorage_no_compile_tests" status="run" time="0" classname="UnitTestPortSenderExtensionCurrentStorage" />
  </testsuite>
  <testsuite name="UnitTestEnvSenderPortExtensionCurrentStorage" tests="12" failures="0" disabled="0" errors="0" time="0.001">
    <testcase name="TEST_UNIT_DADDY_SENDER_TExtensionCurrentStorage_ctor" status="run" time="0" classname="UnitTestEnvSenderPortExtensionCurrentStorage" />
  </testsuite>
</testsuites>
```

The corresponding rst code looks like this:
```
.. test-file:: TEST_UNIT_DADDY_SENDER_TExtensionCurrentStorage
   :id: TEST_UNIT_DADDY_SENDER_TExtensionCurrentStorage
   :tags: unit-test
   :file: unit_tests/daddy_test_unit_port_sender_extension_current_storage_GCC.xml
   :auto_suites:
   :auto_cases:
```

In version 0.3.6 this worked fine. Test reports identified both suites inside the file and I saw all test cases.
As of version 0.3.7, I only see need objects created for the first suite in the xml file.

It probably has something to do with the nested test suite support added in version 0.3.7

**Closed** 2022-10-26 11:46 UTC

**Comment by danwos** [comment] 2022-10-26 11:50
@santiagopagani @sky-dream, the bug got fixed and all testsuites are getting documented now.

Can you please check, if anything is missing or not working for your use case and especially test result data?
Install from ``master`` branch via ``pip install git+https://github.com/useblocks/sphinx-test-reports.git``.
